### ISSUE TITLE
Couldn't start resource redm_extended. :(

### ISSUE THREAD

**Issue by PokeSer** [TigoDevelopment/redm_extended#1]
![image](https://user-images.githubusercontent.com/47903164/80861010-0d8e2f00-8c6c-11ea-8d4f-81341776b7bf.png)
After the last update, redm_extended does not start.

**Comment by ThymonA** [comment]
RDX use two dependencies, have you installed them?
- [Async RedM](https://github.com/TigoDevelopment/redm-async/tree/master) must named `async`
- [MySQL (Async) RedM](https://github.com/TigoDevelopment/redm-mysql-async) must named `mysql-async`

**Comment by PokeSer** [comment]
![image](https://user-images.githubusercontent.com/47903164/80862664-1801f600-8c77-11ea-88c0-7252575dbcda.png) 
![image](https://user-images.githubusercontent.com/47903164/80862675-41228680-8c77-11ea-98eb-56216ac537ab.png)

Yes :(

**Comment by ThymonA** [comment]
I found the problem, i have pushed a new update to mysql-async
https://github.com/TigoDevelopment/redm-mysql-async
If you reinstall that, everything should work.
Remember, I'm still working on making it release ready for RedM, so there might still be some bugs.

**Comment by PokeSer** [comment]
Yes! now it works, thank you very much! Do you have discord of the framework?

**Comment by ThymonA** [comment]
Not yet, will be released later, when framework will be released
