### ISSUE TITLE
cant first connect

### ISSUE THREAD

**Issue by cedricalpatch** [TigoDevelopment/redm_extended#2]
hello I have one problem for connect to the server with your RDX
code error missing-identifier ... but is my first connect 
Steam and Rockstart run and I can connect to my other server

**Comment by cedricalpatch** [comment]
but the rockstar account don't work in redm

**Comment by ThymonA** [comment]
@cedricalpatch I've just done a new installation of RedM Server with RDX.
Run it on build: `2458-e4379363a6ef93498b8b2ffa68c5f60e627f3df7`
Result is: I can join with the Rockstar License ID.
In the coming days I will release an update where identifier can be set using config file like: `steam`, `license`, `xbl`, `discord` etc.
![Showcase](https://cdn.discordapp.com/attachments/707194536249655348/710732465609900032/unknown.png)

**Comment by cedricalpatch** [comment]
Ok may be redm have fix this problem but my problem stay here... I check again but I have 2459 new build of fivem but not resource ... I don't think is the problem!
I lets you know

**Comment by cedricalpatch** [comment]
you have make local or online server?

**Comment by cedricalpatch** [comment]
The Rockstar identifier can't sending to the db with online server ... just local work!?

**Comment by cedricalpatch** [comment]
Resolved just change license: by steam: in function.lua line 296

**Comment by ThymonA** [comment]
An update has just been pushed that solves this problem. Change the [config.lua](https://github.com/TigoDevelopment/redm_extended/blob/master/configs/config.lua#L18) file to the identifier you want to use.
